Installing Helm and adding tests: CY-5792
codacy/codacy-checkov pull request #19
Opened 2022-03-21 15:42 UTC by stefanvacareanu7

2022-03-21 15:59 UTC, h314to commented
I think you forgot to add `.idea/` and `.DS_Store to `.gitignore`

2022-03-21 16:14 UTC, lolgab commented
You can remove the files you committed by mistake, by running:
```
`git rm --cached .idea`
```

2022-03-21 16:41 UTC, lolgab requested changes

2022-03-21 16:41 UTC, lolgab commented on .idea/.gitignore
> +/workspace.xml
You don't need this file if you gitignore the entire directory.

2022-03-21 16:41 UTC, lolgab commented on Dockerfile
> +    apk add --no-cache curl bash openssl; curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3; chmod 700 get_helm.sh; /bin/bash get_helm.sh; rm get_helm.sh
You can install helm from the Alpine packages: https://pkgs.alpinelinux.org/packages?name=helm&branch=edge

2022-11-24 08:46 UTC, stefanvacareanu7 commented
outdated

2022-11-24 08:46 UTC, closed without merging